name: "electron-build-action"
author: "CareScribe"
branding:
  icon: "feather"
  color: "green"
description: ""
inputs:
  command:
    description: ""
    required: true
    default: "--version"    
  username:
    description: ""
    required: false
  password:
    description: ""
    required: false
  credential_id:
    description: ""
    required: false
  totp_secret:
    description: ""
    required: false
  program_name:
    description: ""
    required: false
  file_path:
    description: ""
    required: false
  output_path:
    description: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
